name: Tests Status 🧪

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Choose the desired Python version

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
          source $HOME/.poetry/env

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          poetry install

      - name: Run Pytest
        run: |
          cd ${{ github.workspace }}
          poetry run pytest --junitxml=pytest_report.xml  # Executa pytest usando poetry

      - name: Add XSLT Style to XML Report
        run: |
          echo '<?xml-stylesheet type="text/xsl" href="transformacao.xsl"?>' | cat - pytest_report.xml > temp && mv temp pytest_report.xml    
      
      - name: Upload Pytest Report
        uses: actions/upload-artifact@v4
        with:
          name: Pytest Reports
          path: pytest_report.xml
