name: Tests Status 🧪

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test-env:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x  # Choose the desired Python version
      
      - name: Cache Python Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-          

      - name: Install dependencies
        run:  >-
          python3 -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: python3 -m build

      - name: Store the distribution packages
        uses: actions/upload-artifact@v3
        with:
          name: python-package-distributions
          path: dist/

      - name: Run Pytest
        run: |
          cd ${{ github.workspace }}
          python -m pytest --junitxml=pytest_report.xml  # Gera um arquivo de relatório em formato XML
      
      - name: Add XSLT Style to XML Report
        run: |
          echo '<?xml-stylesheet type="text/xsl" href="transformacao.xsl"?>' | cat - pytest_report.xml > temp && mv temp pytest_report.xml    
      
      - name: Upload Pytest Report
        uses: actions/upload-artifact@v4
        with:
          name: Pytest Reports
          path: pytest_report.xml
